### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by thanhson1085** [BuildOnViction/tomochain-v1#176]
We have one technical issue
We are using golang native etherum package to communicate with tomo

if we are sending a transaction from a wallet to tomo, and before that transaction became confirmed by tomo and we sending a new transaction fro the same wallet addres we are getting an error.

if we wait until the first transaction is successfully confirmed, and after we are sending new transaction everything is ok.

on rinkeby we didnt have this issue

we can solve it now, with a workaround.

but still it is a question why we get this error

we will share now the error message from golang

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x624327]

goroutine 80 [running]:
sync/atomic.(*Value).Load(...)
        /home/smiskey/TFD-Blockchain/sandbox/go/src/github.com/ethereum/go-ethereum/core/types/transaction.go:199
github.com/ethereum/go-ethereum/core/types.(*Transaction).Hash(0x0, 0x0, 0x0, 0x0, 0x0)
        /home/smiskey/TFD-Blockchain/sandbox/go/src/github.com/ethereum/go-ethereum/core/types/transaction.go:199 +0x67
_/home/smiskey/TFD-Blockchain/listener-tomo/common.SolTrAdd(0xc420118900)
        /home/smiskey/TFD-Blockchain/listener-tomo/common/sol.go:67 +0x451
github.com/buaazp/fasthttprouter.(*Router).Handler(0xc4202f4030, 0xc420118900)
        /srv/TFD-Blockchain/gopath/src/github.com/buaazp/fasthttprouter/router.go:300 +0xaab
github.com/buaazp/fasthttprouter.(*Router).Handler-fm(0xc420118900)
        /home/smiskey/TFD-Blockchain/listener-tomo/listener.go:27 +0x34
github.com/valyala/fasthttp.(*Server).serveConn(0xc4200a9040, 0xe15d60, 0xc4204f0000, 0x91a801, 0xc4203b0101)
        /srv/TFD-Blockchain/gopath/src/github.com/valyala/fasthttp/server.go:1566 +0x744
github.com/valyala/fasthttp.(*Server).(github.com/valyala/fasthttp.serveConn)-fm(0xe15d60, 0xc4204f0000, 0x1, 0x0)
        /srv/TFD-Blockchain/gopath/src/github.com/valyala/fasthttp/server.go:1280 +0x3e
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc4200c0580, 0xc4203b6aa0)
        /srv/TFD-Blockchain/gopath/src/github.com/valyala/fasthttp/workerpool.go:210 +0xdc
github.com/valyala/fasthttp.(*workerPool).getCh.func1(0xc4200c0580, 0xc4203b6aa0, 0x85ed80, 0xc4203b6aa0)
        /srv/TFD-Blockchain/gopath/src/github.com/valyala/fasthttp/workerpool.go:182 +0x35
created by github.com/valyala/fasthttp.(*workerPool).getCh
        /srv/TFD-Blockchain/gopath/src/github.com/valyala/fasthttp/workerpool.go:181 +0x13c
```

**Comment by ngtuna** [comment]
TFD replied that they found a work-around solution and they don't have time to investigate more on this issue. This is really out of our scope as they are using their private code to interact to our chain. I am going to close this issue for now. We will go back on this once they give us further information.
