### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by nguyenbatam** [BuildOnViction/tomochain-v1#316]
```INFO [12-03|11:06:10] Updating new set of masternodes
fatal error: concurrent map read and map write

goroutine 35437 [running]:
runtime.throw(0xfd6b80, 0x21)
        /usr/local/go/src/runtime/panic.go:608 +0x72 fp=0xc00902bd08 sp=0xc00902bcd8 pc=0x441d72
runtime.mapaccess2(0xe37940, 0xc04bf22300, 0xc061558a20, 0x1f12c30, 0x4f4b17)
        /usr/local/go/src/runtime/map.go:453 +0x223 fp=0xc00902bd50 sp=0xc00902bd08 pc=0x4232f3
reflect.mapaccess(0xe37940, 0xc04bf22300, 0xc061558a20, 0xfbcaa5)
        /usr/local/go/src/runtime/map.go:1249 +0x3f fp=0xc00902bd88 sp=0xc00902bd50 pc=0x42543f
reflect.Value.MapIndex(0xe37940, 0xc02b650038, 0x195, 0xf062a0, 0xc061558a20, 0x91, 0xe3e540, 0x1f12c30, 0x99)
        /usr/local/go/src/reflect/value.go:1111 +0x11d fp=0xc00902be08 sp=0xc00902bd88 pc=0x4d306d
encoding/json.(*mapEncoder).encode(0xc000424230, 0xc02e346f20, 0xe37940, 0xc02b650038, 0x195, 0x100)
        /usr/local/go/src/encoding/json/encode.go:692 +0x329 fp=0xc00902bf78 sp=0xc00902be08 pc=0x569d39
encoding/json.(*mapEncoder).encode-fm(0xc02e346f20, 0xe37940, 0xc02b650038, 0x195, 0x100)
        /usr/local/go/src/encoding/json/encode.go:708 +0x64 fp=0xc00902bfb8 sp=0xc00902bf78 pc=0x573cd4
encoding/json.(*structEncoder).encode(0xc000335ce0, 0xc02e346f20, 0xf28c00, 0xc02b650000, 0x199, 0x560100)
        /usr/local/go/src/encoding/json/encode.go:647 +0x280 fp=0xc00902c118 sp=0xc00902bfb8 pc=0x5696a0
encoding/json.(*structEncoder).encode-fm(0xc02e346f20, 0xf28c00, 0xc02b650000, 0x199, 0xc02b650100)
        /usr/local/go/src/encoding/json/encode.go:661 +0x64 fp=0xc00902c158 sp=0xc00902c118 pc=0x573c54
encoding/json.(*ptrEncoder).encode(0xc000424320, 0xc02e346f20, 0xef8100, 0xc02b650000, 0x16, 0xef0100)
        /usr/local/go/src/encoding/json/encode.go:788 +0xb3 fp=0xc00902c1a0 sp=0xc00902c158 pc=0x56acb3
encoding/json.(*ptrEncoder).encode-fm(0xc02e346f20, 0xef8100, 0xc02b650000, 0x16, 0xc009020100)
        /usr/local/go/src/encoding/json/encode.go:793 +0x64 fp=0xc00902c1e0 sp=0xc00902c1a0 pc=0x573e54
encoding/json.(*encodeState).reflectValue(0xc02e346f20, 0xef8100, 0xc02b650000, 0x16, 0x1ee0100)
        /usr/local/go/src/encoding/json/encode.go:333 +0x82 fp=0xc00902c218 sp=0xc00902c1e0 pc=0x566fd2
encoding/json.(*encodeState).marshal(0xc02e346f20, 0xef8100, 0xc02b650000, 0xc009020100, 0x0, 0x0)
        /usr/local/go/src/encoding/json/encode.go:305 +0xf4 fp=0xc00902c260 sp=0xc00902c218 pc=0x566a84
encoding/json.Marshal(0xef8100, 0xc02b650000, 0xf12d60, 0xc053089f00, 0xef8100, 0xc02b650000, 0xc053089e00)
        /usr/local/go/src/encoding/json/encode.go:160 +0x52 fp=0xc00902c2d8 sp=0xc00902c260 pc=0x566352
g```

**Comment by ngtuna** [comment]
fixed via https://github.com/tomochain/tomochain/pull/341/commits/a0d36b2fe439a7f3f0444c0d32f56576e84eb7a1
