### ISSUE TITLE
Got an Error when I deploy a smart contract

### ISSUE THREAD

**Issue by thanhson1085** [BuildOnViction/tomochain-v1#42]
I download the latest source code and run a masternode. The node runs properly.

But when I use truffle to deploy a smart contract, I got an error as the below:

```
TRACE[06-19|03:09:23] >> PING/v4                               addr=5.1.83.226:30303    err=nil
TRACE[06-19|03:09:23] >> PING/v4                               addr=191.235.84.50:30303 err=nil
TRACE[06-19|03:09:23] >> PING/v4                               addr=52.16.188.185:30303 err=nil
TRACE[06-19|03:09:23] >> PING/v4                               addr=13.75.154.138:30303 err=nil
TRACE[06-19|03:09:23] >> PING/v4                               addr=13.93.211.84:30303  err=nil
TRACE[06-19|03:09:23] >> PING/v4                               addr=52.74.57.123:30303  err=nil
INFO [06-19|03:09:24] Successfully sealed new block            number=1423 hash=ce3bec…ae3072
DEBUG[06-19|03:09:24] Trie cache stats after commit            misses=0 unloads=0
INFO [06-19|03:09:24] 🔨 mined potential block                  number=1423 hash=ce3bec…ae3072
TRACE[06-19|03:09:24] Propagated block                         hash=ce3bec…ae3072 recipients=0 duration=2562047h47m16.854s
TRACE[06-19|03:09:24] Announced block                          hash=ce3bec…ae3072 recipients=0 duration=2562047h47m16.854s
DEBUG[06-19|03:09:24] Reinjecting stale transactions           count=0
TRACE[06-19|03:09:24] take snapshot                            number=1423 hash=ce3bec…ae3072
INFO [06-19|03:09:24] Debugging info                           number of masternodes=1 previous=0xB68beAD04B5f8ACF4Bfa8013d98f198f861848FF position=0 current=0xB68beAD04B5f8ACF4Bfa8013d98f198f861848FF position=0
INFO [06-19|03:09:24] Commit new mining work                   number=1424 txs=0 uncles=0 elapsed=1.167ms
TRACE[06-19|03:09:24] Waiting for slot to sign and propagate   delay=1.995s
TRACE[06-19|03:09:24] Dial task done                           task="discovery lookup"
TRACE[06-19|03:09:24] New dial task                            task="discovery lookup"
INFO [06-19|03:09:26] Successfully sealed new block            number=1424 hash=911b73…ad2830
DEBUG[06-19|03:09:26] Trie cache stats after commit            misses=0 unloads=0
INFO [06-19|03:09:26] 🔨 mined potential block                  number=1424 hash=911b73…ad2830
TRACE[06-19|03:09:26] Propagated block                         hash=911b73…ad2830 recipients=0 duration=2562047h47m16.854s
TRACE[06-19|03:09:26] Announced block                          hash=911b73…ad2830 recipients=0 duration=2562047h47m16.854s
TRACE[06-19|03:09:26] take snapshot                            number=1424 hash=911b73…ad2830
DEBUG[06-19|03:09:26] Reinjecting stale transactions           count=0
INFO [06-19|03:09:26] Debugging info                           number of masternodes=1 previous=0xB68beAD04B5f8ACF4Bfa8013d98f198f861848FF position=0 current=0xB68beAD04B5f8ACF4Bfa8013d98f198f861848FF position=0
INFO [06-19|03:09:26] Commit new mining work                   number=1425 txs=0 uncles=0 elapsed=827.847µs
TRACE[06-19|03:09:26] Waiting for slot to sign and propagate   delay=1.996s
ERROR[06-19|03:09:27] goroutine 160 [running]:
github.com/ethereum/go-ethereum/rpc.(*Server).serveRequest.func1(0xc4211e8e40, 0x1952240, 0xc420500460)
	/home/vagrant/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:135 +0x11e
panic(0xe9f420, 0x190e110)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/ethereum/go-ethereum/core.(*TxPool).validateTx(0xc42037ddc0, 0xc42c63aea0, 0xc42c67ee01, 0x1ccaac0, 0xe38a9556bc6e22e2)
	/home/vagrant/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:589 +0x322
github.com/ethereum/go-ethereum/core.(*TxPool).add(0xc42037ddc0, 0xc42c63aea0, 0xc42037de01, 0xc420201e10, 0xc42c59136e, 0x2)
	/home/vagrant/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:620 +0xfa
github.com/ethereum/go-ethereum/core.(*TxPool).addTx(0xc42037ddc0, 0xc42c63aea0, 0x1, 0x0, 0x0)
	/home/vagrant/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:792 +0xc0
github.com/ethereum/go-ethereum/core.(*TxPool).AddLocal(0xc42037ddc0, 0xc42c63aea0, 0xc42c67f190, 0x416a6b)
	/home/vagrant/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:762 +0x3f
github.com/ethereum/go-ethereum/eth.(*EthApiBackend).SendTx(0xc420041bd0, 0x194d460, 0xc42005be00, 0xc42c63aea0, 0xc42c63af10, 0xe9dc80)
	/home/vagrant/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/api_backend.go:152 +0x3c
github.com/ethereum/go-ethereum/internal/ethapi.submitTransaction(0x194d460, 0xc42005be00, 0x1955040, 0xc420041bd0, 0xc42c63aea0, 0x0, 0x0, 0x0, 0x0, 0x424cd3, ...)
	/home/vagrant/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/internal/ethapi/api.go:1172 +0xb9
github.com/ethereum/go-ethereum/internal/ethapi.(*PublicTransactionPoolAPI).SendRawTransaction(0xc421016680, 0x194d460, 0xc42005be00, 0xc4200b3c00, 0x3ae, 0x3ae, 0x0, 0x0, 0x0, 0x0, ...)
	/home/vagrant/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/internal/ethapi/api.go:1233 +0x14d
reflect.Value.call(0xc4201bb300, 0xc4211dc520, 0x13, 0xfdafba, 0x4, 0xc4204fe780, 0x3, 0x4, 0x0, 0xc4204fe780, ...)
	/usr/local/go/src/reflect/value.go:434 +0x905
reflect.Value.Call(0xc4201bb300, 0xc4211dc520, 0x13, 0xc4204fe780, 0x3, 0x4, 0x1, 0x1, 0x1)
	/usr/local/go/src/reflect/value.go:302 +0xa4
github.com/ethereum/go-ethereum/rpc.(*Server).handle(0xc4211e8e40, 0x194d460, 0xc42005be00, 0x1952240, 0xc420500460, 0xc4204fe720, 0xc4205004d0, 0x0, 0xe8ac00)
	/home/vagrant/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:311 +0x6ce
github.com/ethereum/go-ethereum/rpc.(*Server).exec(0xc4211e8e40, 0x194d460, 0xc42005be00, 0x1952240, 0xc420500460, 0xc4204fe720)
	/home/vagrant/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:333 +0x1ba
github.com/ethereum/go-ethereum/rpc.(*Server).serveRequest(0xc4211e8e40, 0x1952240, 0xc420500460, 0xfe6601, 0x1, 0x0, 0x0)
	/home/vagrant/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:194 +0x38f
github.com/ethereum/go-ethereum/rpc.(*Server).ServeSingleRequest(0xc4211e8e40, 0x1952240, 0xc420500460, 0x1)
	/home/vagrant/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:225 +0x4e
github.com/ethereum/go-ethereum/rpc.(*Server).ServeHTTP(0xc4211e8e40, 0x194c060, 0xc4202a8c40, 0xc42064d700)
	/home/vagrant/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/http.go:177 +0x25d
github.com/ethereum/go-ethereum/vendor/github.com/rs/cors.(*Cors).Handler.func1(0x194c060, 0xc4202a8c40, 0xc42064d700)
	/home/vagrant/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/rs/cors/cors.go:190 +0x108
net/http.HandlerFunc.ServeHTTP(0xc4211e9600, 0x194c060, 0xc4202a8c40, 0xc42064d700)
	/usr/local/go/src/net/http/server.go:1918 +0x44
github.com/ethereum/go-ethereum/rpc.(*virtualHostHandler).ServeHTTP(0xc4211e9620, 0x194c060, 0xc4202a8c40, 0xc42064d700)
	/home/vagrant/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/http.go:235 +0x208
net/http.serverHandler.ServeHTTP(0xc4211f9790, 0x194c060, 0xc4202a8c40, 0xc42064d700)
	/usr/local/go/src/net/http/server.go:2619 +0xb4
net/http.(*conn).serve(0xc42c648820, 0x194d460, 0xc42005bd00)
	/usr/local/go/src/net/http/server.go:1801 +0x71d
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2720 +0x288
 
TRACE[06-19|03:09:27] Starting bonding ping/pong               id=979b7fa28feeb35a known=false failcount=9  age=424827h9m27.917817329s
TRACE[06-19|03:09:27] Starting bonding ping/pong               id=78de8a0916848093 known=false failcount=9  age=424827h9m27.917986362s
TRACE[06-19|03:09:27] >> PING/v4                               addr=191.235.84.50:30303 err=nil
TRACE[06-19|03:09:27] Starting bonding ping/pong               id=158f8aab45f6d19c known=false failcount=8  age=424827h9m27.91869581s
TRACE[06-19|03:09:27] Starting bonding ping/pong               id=1118980bf48b0a36 known=false failcount=10 age=424827h9m27.918777305s
TRACE[06-19|03:09:27] >> PING/v4                               addr=13.75.154.138:30303 err=nil
TRACE[06-19|03:09:27] Starting bonding ping/pong               id=a979fb575495b8d6 known=false failcount=6  age=424827h9m27.918811492s
TRACE[06-19|03:09:27] >> PING/v4                               addr=52.74.57.123:30303  err=nil
TRACE[06-19|03:09:27] Starting bonding ping/pong               id=3f1d12044546b763 known=false failcount=10 age=424827h9m27.918837901s
TRACE[06-19|03:09:27] >> PING/v4                               addr=5.1.83.226:30303    err=nil
TRACE[06-19|03:09:27] >> PING/v4                               addr=52.16.188.185:30303 err=nil
TRACE[06-19|03:09:27] >> PING/v4                               addr=13.93.211.84:30303  err=nil
INFO [06-19|03:09:28] Successfully sealed new block            number=1425 hash=7357af…d4850c
DEBUG[06-19|03:09:28] Trie cache stats after commit            misses=0 unloads=0
INFO [06-19|03:09:28] 🔨 mined potential block                  number=1425 hash=7357af…d4850c
TRACE[06-19|03:09:28] take snapshot                            number=1425 hash=7357af…d4850c
INFO [06-19|03:09:28] Debugging info                           number of masternodes=1 previous=0xB68beAD04B5f8ACF4Bfa8013d98f198f861848FF position=0 current=0xB68beAD04B5f8ACF4Bfa8013d98f198f861848FF position=0
INFO [06-19|03:09:28] Commit new mining work                   number=1426 txs=0 uncles=0 elapsed=1.194ms
TRACE[06-19|03:09:28] Propagated block                         hash=7357af…d4850c recipients=0 duration=2562047h47m16.854s
TRACE[06-19|03:09:28] Announced block                          hash=7357af…d4850c recipients=0 duration=2562047h47m16.854s
DEBUG[06-19|03:09:28] Reinjecting stale transactions           count=0
TRACE[06-19|03:09:28] Waiting for slot to sign and propagate   delay=1.996s
TRACE[06-19|03:09:28] Dial task done                           task="discovery lookup"
TRACE[06-19|03:09:28] New dial task                            task="discovery lookup"
INFO [06-19|03:09:30] Successfully sealed new block            number=1426 hash=c3b4be…69549b
DEBUG[06-19|03:09:30] Trie cache stats after commit            misses=0 unloads=0
INFO [06-19|03:09:30] 🔗 block reached canonical chain          number=1421 hash=0c2bf6…2a7563
INFO [06-19|03:09:30] 🔨 mined potential block                  number=1426 hash=c3b4be…69549b
DEBUG[06-19|03:09:30] Reinjecting stale transactions           count=0
TRACE[06-19|03:09:30] Propagated block                         hash=c3b4be…69549b recipients=0 duration=2562047h47m16.854s
TRACE[06-19|03:09:30] Announced block                          hash=c3b4be…69549b recipients=0 duration=2562047h47m16.854s
TRACE[06-19|03:09:30] take snapshot                            number=1426 hash=c3b4be…69549b
INFO [06-19|03:09:30] Debugging info                           number of masternodes=1 previous=0xB68beAD04B5f8ACF4Bfa8013d98f198f861848FF position=0 current=0xB68beAD04B5f8ACF4Bfa8013d98f198f861848FF position=0
INFO [06-19|03:09:30] Commit new mining work                   number=1427 txs=0 uncles=0 elapsed=1.612ms
TRACE[06-19|03:09:30] Waiting for slot to sign and propagate   delay=1.996s
```

**Comment by dinhln89** [comment]
Hi @thanhson1085. Please send to me more information about command line that you have to started this node. Thanks!

**Comment by thanhson1085** [comment]
Yep, the command I used is:
```
echo Starting the node ...
./build/bin/tomo --datadir ./build/tomochain --networkid 889 --rpc --rpccorsdomain "*" --rpcaddr 0.0.0.0 --rpcport 8545 --rpcvhosts "*" --unlock "${wallet}" --password ./build/.pwd --mine --gasprice "0" --targetgaslimit "420000000" --verbosity 5
```

**Comment by dinhln89** [comment]
Okay, thank for your report. I saw this bug. I will fix it ASAP ^^!

**Comment by dinhln89** [comment]
I have just create PR for hot fix this bug. Please help me review it. Many thanks!

https://github.com/tomochain/tomochain/pull/45
