### ISSUE TITLE
when i tried to run tomochain code in  mist wallet it shows me the following error

### ISSUE THREAD

**Issue by richardwing121** [BuildOnViction/tomochain-v1#506]
[2019-05-03T10:48:00.007] [INFO] EthereumNode - INFO [05-03|10:48:00] Stats daemon started 
INFO [05-03|10:48:00] RLPx listener up                         self=enode://f7defb936186a7c8342f45900a61674069c0ee2d7bcb24c147ce6ead7e98370acc180930b69a1191f01907b2b1c624f827c343b4802c9218e250b2f36cd00e74@[::]:30303

[2019-05-03T10:48:00.013] [INFO] EthereumNode - INFO [05-03|10:48:00] IPC endpoint opened                      url=/home/richard/.tomo/tomo.ipc

[2019-05-03T10:48:00.014] [INFO] EthereumNode - INFO [05-03|10:48:00] HTTP endpoint opened                     url=http://127.0.0.1:8545     cors= vhosts=localhost
INFO [05-03|10:48:00] WebSocket endpoint opened                url=ws://127.0.0.1:8546
INFO [05-03|10:48:00] Etherbase automatically configured       address=0xDC959caa3D30e84b0eF238F6C37d58a872582428

[2019-05-03T10:48:06.599] [INFO] EthereumNode - 9000ms elapsed, assuming node started up successfully
[2019-05-03T10:48:06.600] [INFO] EthereumNode - Started node successfully: tomo ropsten full
[2019-05-03T10:48:06.602] [INFO] Sockets/node-ipc - Connect to {"path":"/home/richard/.tomo/tomo.ipc"}
[2019-05-03T10:48:06.604] [INFO] Sockets/node-ipc - Connected!
[2019-05-03T10:48:06.605] [INFO] Sockets/3 - Connect to {"path":"/home/richard/.tomo/tomo.ipc"}
[2019-05-03T10:48:06.608] [INFO] Sockets/3 - Connected!
[2019-05-03T10:48:09.417] [INFO] EthereumNode - INFO [05-03|10:48:09] Block synchronisation started 

[2019-05-03T10:48:17.579] [INFO] EthereumNode - INFO [05-03|10:48:17] Imported new block headers               count=0 elapsed=214.511ms number=384 hash=29d8b0…a4bae8 ignored=384

[2019-05-03T10:48:17.586] [INFO] EthereumNode - INFO [05-03|10:48:17] Imported new block receipts              count=0 elapsed=64.601µs  number=2   hash=b60948…3489ab size=0.00B ignored=2

[2019-05-03T10:48:21.057] [INFO] EthereumNode - INFO [05-03|10:48:21] Imported new block headers               count=0 elapsed=228.558ms number=768 hash=9616da…61149a ignored=384

[2019-05-03T10:48:21.282] [INFO] EthereumNode - INFO [05-03|10:48:21] Imported new state entries               count=357 elapsed=3.060ms   processed=357 pending=718 retry=0 duplicate=0 unexpected=0

[2019-05-03T10:48:22.028] [INFO] EthereumNode - INFO [05-03|10:48:22] Imported new block receipts              count=82  elapsed=16.383ms  number=84  hash=2af6ae…c426e1 size=183.09kB ignored=0

[2019-05-03T10:48:22.114] [INFO] EthereumNode - panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6d0b3a]

goroutine 934 [running]:
github.com/ethereum/go-ethereum/core/types.(*Block).Hash(0x0, 0x0, 0x0, 0x0, 0x0)
        /home/richard/github/tomo/tomochain/build/_workspace/src/github.com/ethereum/go-ethereum/core/types/block.go:420 +0x4a
github.com/ethereum/go-ethereum/contracts.GetSigners(0xc001d270e0, 0x0, 0xceab49ca27cf8056, 0x2a33f5973e07bb41, 0xfac43b2b991db973)

[2019-05-03T10:48:22.115] [INFO] EthereumNode - /home/richard/github/tomo/tomochain/build/_workspace/src/github.com/ethereum/go-ethereum/contracts/blockSignerReader.go:19 +0x81
github.com/ethereum/go-ethereum/contracts.GetSignersFromContract(0xc001d270e0, 0x0, 0xceab49ca27cf8056, 0x2a33f5973e07bb41, 0xfac43b2b991db973, 0x0, 0x0)
        /home/richard/github/tomo/tomochain/build/_workspace/src/github.com/ethereum/go-ethereum/contracts/utils.go:202 +0x35
github.com/ethereum/go-ethereum/eth.New.func4(0x123d740, 0xc00041a360, 0x384, 0x3, 0xb11102b9ef1ca00d, 0xe74cb9ad6ecc86b5, 0xc8a670db38c70ee6, 0xd9437f05890e7a30)
        /home/richard/github/tomo/tomochain/build/_workspace/src/github.com/ethereum/go-ethereum/eth/backend.go:294 +0x432
github.com/ethereum/go-ethereum/consensus/posv.(*posv).verifyCascadingFields(0xc0001224d0, 0x123d740, 0xc00041a360, 0xc001248f00, 0xc0012e4000, 0x83, 0x3c0, 0x71a800, 0xc00011e350, 0xf27920)
        /home/richard/github/tomo/tomochain/build/_workspace/src/github.com/ethereum/go-ethereum/consensus/posv/posv.go:408 +0x8cc
github.com/ethereum/go-ethereum/consensus/posv.(*posv).verifyHeader(0xc0001224d0, 0x123d740, 0xc00041a360, 0xc001248f00, 0xc0012e4000, 0x83, 0x3c0, 0x46f700, 0xc0196eff28, 0x2)
        /home/richard/github/tomo/tomochain/build/_workspace/src/github.com/ethereum/go-ethereum/consensus/posv/posv.go:368 +0x37d
github.com/ethereum/go-ethereum/consensus/posv.(*posv).verifyHeaderWithCache(0xc0001224d0, 0x123d740, 0xc00041a360, 0xc001248f00, 0xc0012e4000, 0x83, 0x3c0, 0x9e8c00, 0x0, 0x0)
        /home/richard/github/tomo/tomochain/build/_workspace/src/github.com/ethereum/go-ethereum/consensus/posv/posv.go:299 +0x120
github.com/ethereum/go-ethereum/consensus/posv.(*posv).VerifyHeaders.func1(0xc0012e4000, 0x3c0, 0x3c0, 0xc0001224d0, 0x123d740, 0xc00041a360, 0xc01b10a400, 0x3c0, 0x3c0, 0xc01b5a84e0, ...)
        /home/richard/github/tomo/tomochain/build/_workspace/src/github.com/ethereum/go-ethereum/consensus/posv/posv.go:282 +0x12f
created by github.com/ethereum/go-ethereum/consensus/posv.(*posv).VerifyHeaders
        /home/richard/github/tomo/tomochain/build/_workspace/src/github.com/ethereum/go-ethereum/consensus/posv/posv.go:280 +0x10a

**Comment by ngtuna** [comment]
it looks like you got trouble in the first epoch. Can you try to change this line of code https://github.com/tomochain/tomochain/blob/master/eth/backend.go#L282 to 

```
if prevEpoc > 0 
```

Then build it with `make tomo` command. And try again to see if the issue disappears

**Comment by ngtuna** [comment]
I am closing this. Re-open it once you have more info. @richardwing121
